import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'
import styles from '../styles/Layout.module.scss'
import Navbar from './Navbar'

export default function Layout({ children }) {

  return (
    <React.Fragment>
      <Head>
        <title>This is Galih!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <Navbar />
        <div className={styles.content}>
          {children}
        </div>
      </div>
    </React.Fragment >
  )
}