import React from 'react'
import Head from 'next/head'
import styles from '../styles/WelcomePage.module.scss'
import Card from '../components/Card'
import Button from '../components/Button'
import Link from 'next/link'

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>This is Galih!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
        <div className={`slideFrom-top ${styles.body}`}>
          <Card>
            <div className={styles.message}>
              <h2 className={`blinking ${styles.message__header}`}>
                Hello there!
              </h2>
              <p className={styles.message__body}>
                Where are you come from? Mars? Pluto? Ah it doesn't matter.
                I'm really glad you were here, at least for now hahaha.
              </p>

              <p className={styles.message__body}>
                Actualy this is my personal site, the place where I used to record my achievment
                and my amazing journey became programmer.
              </p>

              <p className={styles.message__body}>
                Since you were here, let's get to know more about me!
              </p>

              <div className={`${styles.message__footer}`}>
                <Button style={{ margin: "0 auto" }}>
                  <Link href="/profile">
                    <a>Come On!</a>
                  </Link>
                </Button>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </React.Fragment >
  )
}
